services:
  - type: web
    name: smart-expense-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 8000
